<?php
	if(isset($_GET['path'])){
		$path=$_GET['path'];
		$out=[];
		if(file_exists($path)){
			if(is_file($path)){
				$out=[
					"path"=>$path,
					"status"=>"exist",
					"type"=>"file",
					"filesize"=>filesize($path),
					"mime"=>mime_content_type($path),
					"md5"=>md5_file($path),
					"modifyed"=>filemtime($path)
				];
			}elseif(is_dir($path)){
				$out=[
					"path"=>$path,
					"status"=>"exist",
					"type"=>"dir",
					"filesize"=>filesize($path)
				];
			}
		}else{
			$out=[
				"path"=>$path,
				"status"=>"not_exist"
			];
		}
		json_output($out);
	}else{
		json_output([
			'error'=>'$_GET["path"] not set!'
		]);
	}
?>