name: Docker Image CI

on:
  release:
    types: [ published ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set tag for image
      run: tagname=$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t sarverott/rokita:$tagname
    - name: Release public image in docker's repo
      run: docker push sarverott/rokita:$tagname
